/**
 * SPK SERVICE - Business Logic Layer
 * 
 * KATEGORI 2: Tuntunan Backend - API INPUT/WRITE
 * Sub-Proses 1 & 2: INTEL & PLAN + EKSEKUSI & LAPOR
 * 
 * Filosofi 3P:
 * - SIMPLE: Logic bisnis terpisah dari routing
 * - TEPAT: Validasi data, Jejak Digital 5W1H mandatory
 * - PENINGKATAN BERTAHAB: Auto-trigger Work Order baru
 * 
 * Tuntunan Keamanan: 
 * - Semua input dari HP harus divalidasi ulang di server
 * - UserID dari JWT (jangan percaya input manual)
 * - Timestamp server (bukan dari HP)
 * 
 * Tuntunan Skalabilitas:
 * - Transaction untuk operasi multi-tabel
 * - Indexing pada kolom yang sering di-query
 */

const { supabase } = require('../config/supabase');

// ============================================================
// FITUR M-4.1: CREATE SPK HEADER
// ============================================================

/**
 * Create SPK Header (Induk Penugasan)
 * 
 * TUJUAN: Insert data SPK baru ke tabel spk_header
 * FITUR: M-4.1
 * SUB-PROSES: SP-1 (Intel & Plan) - Organizing
 * 
 * INPUT:
 * {
 *   nama_spk: string (required, max 255),
 *   id_asisten_pembuat: string (required, FK ke master_pihak),
 *   tanggal_target_selesai: string (optional, ISO 8601 date),
 *   keterangan: string (optional, max 5000)
 * }
 * 
 * OUTPUT:
 * {
 *   id_spk: string (UUID generated by Supabase),
 *   nama_spk: string,
 *   id_asisten_pembuat: string,
 *   tanggal_dibuat: string (ISO 8601 timestamp, server-side),
 *   tanggal_target_selesai: string,
 *   status_spk: string (default: 'BARU'),
 *   keterangan: string
 * }
 * 
 * VALIDASI BISNIS:
 * 1. id_asisten_pembuat harus exist di tabel master_pihak (FK constraint)
 * 2. status_spk default = 'BARU'
 * 3. tanggal_dibuat diambil dari server (getdate()), bukan dari client
 * 
 * ERROR HANDLING:
 * - Throw error jika INSERT gagal
 * - Error FK violation akan di-catch oleh router layer
 */
async function createSpkHeader(spkData) {
  try {
    console.log('📝 [Service] Creating SPK Header...');
    console.log('   Input:', JSON.stringify(spkData, null, 2));
    
    // Prinsip KEAMANAN: Sanitasi input
    // Trim whitespace dari semua string inputs
    const sanitizedData = {
      nama_spk: spkData.nama_spk.trim(),
      id_asisten_pembuat: spkData.id_asisten_pembuat.trim(),
      // Optional fields
      tanggal_target_selesai: spkData.tanggal_target_selesai || null,
      keterangan: spkData.keterangan ? spkData.keterangan.trim() : null
    };
    
    // Prinsip TEPAT: Validasi business rule - id_asisten_pembuat harus exist
    // (Di real world, kita cek dulu ke master_pihak, tapi Supabase FK akan handle ini)
    const { data: asistenExists, error: checkError } = await supabase
      .from('master_pihak')
      .select('id_pihak')
      .eq('id_pihak', sanitizedData.id_asisten_pembuat)
      .single();
    
    if (checkError || !asistenExists) {
      throw new Error(`ID Asisten Pembuat '${sanitizedData.id_asisten_pembuat}' tidak ditemukan di master_pihak`);
    }
    
    console.log('✅ ID Asisten valid:', asistenExists.id_pihak);
    
    // INSERT ke tabel spk_header
    // Catatan: 
    // - id_spk akan auto-generated oleh Supabase (DEFAULT gen_random_uuid())
    // - tanggal_dibuat akan auto-filled oleh Supabase (DEFAULT now())
    // - status_spk akan auto-filled oleh Supabase (DEFAULT 'BARU')
    const { data, error } = await supabase
      .from('spk_header')
      .insert([
        {
          nama_spk: sanitizedData.nama_spk,
          id_asisten_pembuat: sanitizedData.id_asisten_pembuat,
          tanggal_target_selesai: sanitizedData.tanggal_target_selesai,
          keterangan: sanitizedData.keterangan
          // id_spk, tanggal_dibuat, status_spk akan auto-generated
        }
      ])
      .select(); // PENTING: .select() untuk return data yang baru di-insert
    
    if (error) {
      console.error('❌ [Service] Supabase INSERT error:', error);
      throw new Error(`Gagal insert SPK Header: ${error.message}`);
    }
    
    if (!data || data.length === 0) {
      throw new Error('Gagal insert SPK Header: No data returned');
    }
    
    const newSpk = data[0];
    console.log('✅ [Service] SPK Header created successfully!');
    console.log('   ID SPK:', newSpk.id_spk);
    console.log('   Status:', newSpk.status_spk);
    console.log('   Tanggal Dibuat:', newSpk.tanggal_dibuat);
    
    // Return data sesuai kontrak API
    return {
      id_spk: newSpk.id_spk,
      nama_spk: newSpk.nama_spk,
      id_asisten_pembuat: newSpk.id_asisten_pembuat,
      tanggal_dibuat: newSpk.tanggal_dibuat,
      tanggal_target_selesai: newSpk.tanggal_target_selesai,
      status_spk: newSpk.status_spk,
      keterangan: newSpk.keterangan
    };
    
  } catch (err) {
    console.error('❌ [Service] Error in createSpkHeader:', err.message);
    throw err; // Re-throw untuk di-catch oleh router layer
  }
}

// ============================================================
// FITUR M-4.2: ADD TUGAS KE SPK (BATCH INSERT)
// ============================================================

/**
 * Add Tugas ke SPK (Batch Insert)
 * 
 * TUJUAN: Insert multiple tugas ke tabel spk_tugas dalam satu transaksi
 * FITUR: M-4.2
 * SUB-PROSES: SP-1 (Intel & Plan) - Organizing (Breakdown)
 * 
 * INPUT:
 * - id_spk: string (UUID, from URL parameter)
 * - arrayTugas: array of objects
 *   [
 *     {
 *       id_pelaksana: string (UUID, FK ke master_pihak),
 *       tipe_tugas: string (max 15 chars, FK ke tupoksi_tipe),
 *       target_json: object (blok, id_pohon, dll),
 *       prioritas: number (optional, 1-3, default: 2)
 *     }
 *   ]
 * 
 * OUTPUT:
 * {
 *   id_spk: string,
 *   jumlah_tugas_ditambahkan: number,
 *   tugas: array of created tasks with id_tugas
 * }
 * 
 * VALIDASI BISNIS:
 * 1. id_spk harus exist di tabel spk_header
 * 2. id_pelaksana harus exist di tabel master_pihak (FK constraint)
 * 3. tipe_tugas harus exist di tabel tupoksi_tipe (FK constraint)
 * 4. target_json harus valid JSON (akan di-stringify jika object)
 * 5. prioritas default = 2 (Sedang) jika tidak diisi
 * 6. status_tugas default = 'BARU' (dari database default)
 * 
 * PRINSIP MPP:
 * - SIMPLE: Batch insert dalam 1 call
 * - TEPAT: Validasi FK untuk setiap item, sanitasi input
 * - PENINGKATAN BERTAHAB: Auto-generated id_tugas, status_tugas
 */
async function addTugasKeSpk(id_spk, arrayTugas) {
  try {
    console.log('📝 [Service] Adding tugas to SPK...');
    console.log('   ID SPK:', id_spk);
    console.log('   Jumlah Tugas:', arrayTugas.length);
    
    // Prinsip TEPAT: Validasi bahwa SPK Header exist
    const { data: spkExists, error: spkError } = await supabase
      .from('spk_header')
      .select('id_spk, nama_spk, status_spk')
      .eq('id_spk', id_spk)
      .single();
    
    if (spkError || !spkExists) {
      throw new Error(`SPK dengan ID '${id_spk}' tidak ditemukan`);
    }
    
    console.log('✅ SPK ditemukan:', spkExists.nama_spk);
    console.log('   Status SPK:', spkExists.status_spk);
    
    // Prinsip KEAMANAN: Validasi FK untuk setiap tugas
    // 1. Validasi semua id_pelaksana exist di master_pihak
    const uniquePelaksanaIds = [...new Set(arrayTugas.map(t => t.id_pelaksana))];
    console.log('🔍 Validasi ID Pelaksana:', uniquePelaksanaIds);
    
    const { data: pelaksanaData, error: pelaksanaError } = await supabase
      .from('master_pihak')
      .select('id_pihak')
      .in('id_pihak', uniquePelaksanaIds);
    
    if (pelaksanaError) {
      throw new Error(`Gagal validasi ID Pelaksana: ${pelaksanaError.message}`);
    }
    
    const foundPelaksanaIds = pelaksanaData.map(p => p.id_pihak);
    const missingPelaksanaIds = uniquePelaksanaIds.filter(id => !foundPelaksanaIds.includes(id));
    
    if (missingPelaksanaIds.length > 0) {
      throw new Error(`ID Pelaksana tidak ditemukan: ${missingPelaksanaIds.join(', ')}`);
    }
    
    console.log('✅ Semua ID Pelaksana valid');
    
    // 2. Validasi semua tipe_tugas exist di tupoksi_tipe (optional, bisa skip jika tidak ada tabel)
    // NOTE: Jika tabel tupoksi_tipe belum ada, comment validasi ini
    const uniqueTipeTugas = [...new Set(arrayTugas.map(t => t.tipe_tugas))];
    console.log('🔍 Tipe Tugas:', uniqueTipeTugas);
    
    // Skip FK validation untuk tipe_tugas jika tabel tupoksi_tipe tidak ada
    // Uncomment kode di bawah jika tabel tupoksi_tipe sudah dibuat:
    /*
    const { data: tipeTugasData, error: tipeTugasError } = await supabase
      .from('tupoksi_tipe')
      .select('kode_tipe')
      .in('kode_tipe', uniqueTipeTugas);
    
    if (tipeTugasError) {
      console.log('⚠️  Warning: Tabel tupoksi_tipe tidak ada, skip validasi tipe_tugas');
    } else {
      const foundTipeTugas = tipeTugasData.map(t => t.kode_tipe);
      const missingTipeTugas = uniqueTipeTugas.filter(tipe => !foundTipeTugas.includes(tipe));
      
      if (missingTipeTugas.length > 0) {
        throw new Error(`Tipe Tugas tidak valid: ${missingTipeTugas.join(', ')}`);
      }
      
      console.log('✅ Semua Tipe Tugas valid');
    }
    */
    
    // Prinsip KEAMANAN: Sanitasi dan prepare data untuk batch insert
    const tugasToInsert = arrayTugas.map(tugas => {
      // Sanitasi string inputs
      const sanitized = {
        id_spk: id_spk.trim(),
        id_pelaksana: tugas.id_pelaksana.trim(),
        tipe_tugas: tugas.tipe_tugas.trim().toUpperCase(), // Normalize ke uppercase
        // target_json: harus di-stringify jika object (Supabase PostgreSQL jsonb)
        target_json: typeof tugas.target_json === 'string' 
          ? tugas.target_json 
          : JSON.stringify(tugas.target_json),
        prioritas: tugas.prioritas || 2 // Default: 2 (Sedang)
        // id_tugas, status_tugas akan auto-generated oleh database
      };
      
      return sanitized;
    });
    
    console.log('📦 Prepared data untuk insert:', tugasToInsert.length, 'tugas');
    
    // BATCH INSERT ke tabel spk_tugas
    // Prinsip SKALABILITAS: Insert multiple rows dalam 1 query
    const { data, error } = await supabase
      .from('spk_tugas')
      .insert(tugasToInsert)
      .select(); // PENTING: .select() untuk return data yang baru di-insert
    
    if (error) {
      console.error('❌ [Service] Supabase BATCH INSERT error:', error);
      throw new Error(`Gagal insert tugas: ${error.message}`);
    }
    
    if (!data || data.length === 0) {
      throw new Error('Gagal insert tugas: No data returned');
    }
    
    console.log('✅ [Service] Batch insert berhasil!');
    console.log('   Jumlah tugas ditambahkan:', data.length);
    
    // Return data sesuai kontrak API
    return {
      id_spk: id_spk,
      jumlah_tugas_ditambahkan: data.length,
      tugas: data.map(t => ({
        id_tugas: t.id_tugas,
        id_pelaksana: t.id_pelaksana,
        tipe_tugas: t.tipe_tugas,
        status_tugas: t.status_tugas,
        target_json: typeof t.target_json === 'string' 
          ? JSON.parse(t.target_json) 
          : t.target_json,
        prioritas: t.prioritas
      }))
    };
    
  } catch (err) {
    console.error('❌ [Service] Error in addTugasKeSpk:', err.message);
    throw err; // Re-throw untuk di-catch oleh router layer
  }
}

// ============================================================
// PLACEHOLDER FUNCTIONS (BELUM DIIMPLEMENTASIKAN)
// ============================================================

/**
 * 1. Create Work Order (SPK Tugas - Detail)
 * [PLACEHOLDER - Belum diimplementasikan]
 * 
 * Catatan: Ini berbeda dengan createSpkHeader.
 * - createSpkHeader = Buat SPK Induk (Header)
 * - createWorkOrder = Buat Tugas Spesifik (Detail) yang terikat ke SPK Header
 */
async function createWorkOrder(data) {
  // TODO: Implementasi create Work Order (spk_tugas)
  throw new Error('Function createWorkOrder belum diimplementasikan');
}

/**
 * 2. Lapor Validasi + Auto-Trigger
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function laporValidasi(data) {
  // TODO: Implementasi lapor validasi
  // TODO: Implementasi auto-trigger WO APH/Sanitasi
  throw new Error('Function laporValidasi belum diimplementasikan');
}

/**
 * 3. Lapor APH
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function laporAph(data) {
  // TODO: Implementasi lapor APH
  throw new Error('Function laporAph belum diimplementasikan');
}

/**
 * 4. Lapor Sanitasi
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function laporSanitasi(data) {
  // TODO: Implementasi lapor sanitasi
  throw new Error('Function laporSanitasi belum diimplementasikan');
}

/**
 * 5. Get Daftar Tugas (dengan Paginasi)
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function getDaftarTugas(filters) {
  // TODO: Implementasi get daftar tugas
  // TODO: Implementasi paginasi
  throw new Error('Function getDaftarTugas belum diimplementasikan');
}

// ============================================================
// HELPER FUNCTIONS (PLACEHOLDER)
// ============================================================

/**
 * Helper: Validasi input data
 * [PLACEHOLDER - Belum diimplementasikan]
 */
function validateInput(data, requiredFields) {
  // TODO: Implementasi validasi
  // Contoh: Check required fields, tipe data, format
  return { valid: true, errors: [] };
}

/**
 * Helper: Auto-trigger Work Order berdasarkan kondisi
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function autoTriggerWorkOrder(statusAktual, idNpokok) {
  // TODO: Implementasi auto-trigger logic
  // IF statusAktual = 'G1' -> createWorkOrder({ tipe_tugas: 'APH', ... })
  // IF statusAktual = 'G3' OR 'G4' -> createWorkOrder({ tipe_tugas: 'SANITASI', ... })
  return null;
}

/**
 * Helper: Insert Log Aktivitas 5W1H
 * [PLACEHOLDER - Belum diimplementasikan]
 */
async function insertLogAktivitas5W1H(data) {
  // TODO: Implementasi insert log
  // Wajib capture: Who, What, When, Where, Why, How
  return null;
}

// ============================================================
// EXPORTS
// ============================================================

module.exports = {
  createSpkHeader,
  addTugasKeSpk,
  createWorkOrder,
  laporValidasi,
  laporAph,
  laporSanitasi,
  getDaftarTugas,
  // Export helpers untuk testing (optional)
  validateInput,
  autoTriggerWorkOrder,
  insertLogAktivitas5W1H
};
